server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: dubbo-demo-spring-cloud-consumer
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 10.39.75.65:18848
        username: nacos
        password: nacos

dubbo:
  consumer:
    check: false
    timeout: 10000

  application:
    id: dubbo-demo-spring-cloud-consumer

  protocol:
    name: dubbo
    port: 20880
  cloud:
    subscribed-services: dubbo-demo-spring-cloud-provider1,dubbo-demo-spring-cloud-provider2
