server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: dubbo-demo-spring-cloud-provider
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 127.0.0.1:8848

dubbo:
  provider:
    validation: true

  application:
    id: dubbo-demo-spring-cloud-provider

  protocol:
    name: dubbo
